### PR TITLE
Minor spelling fix

### PR DESCRIPTION
**Pull request by manuel-uberti**
Just a spelling fix and a whitespace, nothing to be afraid of. ;)

### CODE REVIEW

**Comment by deg** [comment]
Thanks

**Comment by deg** [comment]
What just happened???   I accepted this change, but it does not seem to be in the repo.
Something went wrong? Or github is being slow??  Whatever. I'll do this manually if it does not appear in a couple of hours.

**Comment by manuel-uberti** [comment]
Not sure, to be honest.

**Comment by manuel-uberti** [comment]
It worked on my other PR on sodium, though. Weird.

**Pull request closed without merging**
